#!/bin/sh

# QC & trimming
trim_galore --no_report_file --cores 8 -o --paired *.fq

# mapping
idx=${0%/*}
for fq in $(ls *_1.fq); do
  bamfile="${fq%_1.*}"
  echo $bamfile
  bowtie2 -p 8 -x ${idx}/bt2Build_mm10/mm10 -1 ${bamfile}_1.fq -2 ${bamfile}_2.fq |
    samtools view -bSu -F 4 - |
    pv |
    samtools sort -@ 4 -o ${bamfile}.bam -
  samtools index -b ${bamfile}.bam
done

# convert wig generated by MEDIPS to bigwig
chrom=${0%/*}/mm10.chrom.sizes.txt
for wig in $(ls *.wig); do
  bw=${wig%.*}.bw
  wigToBigWig $wig $chrom $bw
done

# computeMatrix
computeMatrix reference-point --skipZeros -p 6 -bs 100 -a 2500 -b 2500 --referencePoint center -o 5mC_narrowPeak.txt.gz -R *.narrowPeak *.broadPeak -S 1KO_5mC_G1.bw 1KO_5mC_G2.bw 1KO_5hmC_G1.bw 1KO_5hmC_G2.bw